// ****************************************************************
// This file is auto-generated by ifrit.reflparser.
// Do not edit this file manually.
// ****************************************************************

#include "misc.reflection.generated.h"

// Begin Body
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\Asset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\importer\GameObjectPrefabImporter.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\importer\VDBAssetImpoter.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\MaterialAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\mesh\WaveFrontAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\MeshAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\prefab\GameObjectPrefabAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\PrefabAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\ShaderAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\TextureAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\util\PrefabSerializer.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\volume\VDBAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\VolumeAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\ActorBehavior.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\AssetReference.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\Camera.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\Component.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\Light.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\MeshComponent.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\Prefab.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\Scene.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\Transform.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\geometry\preset\Circle2D.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\geometry\preset\Square2D.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\material\SyaroDefaultGBufEmitter.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\physics\artemis\mpm\MPMParticleContainer.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\physics\artemis\mpm\MPMParticleEmitter.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\physics\artemis\mpm\MPMSimulatorConfigurator.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\physics\artemis\pbd\PBDCloth.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\physics\artemis\rigid\GpuRigidCollider.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\renderer\ayanami\AyanamiMeshDF.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\renderer\ayanami\AyanamiMeshMarker.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\Asset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\importer\GameObjectPrefabImporter.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\importer\VDBAssetImpoter.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\MaterialAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\mesh\WaveFrontAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\MeshAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\prefab\GameObjectPrefabAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\PrefabAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\ShaderAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\TextureAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\util\PrefabSerializer.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\volume\VDBAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\asset\VolumeAsset.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\ActorBehavior.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\AssetReference.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\Camera.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\Component.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\Light.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\MeshComponent.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\Prefab.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\Scene.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\base\Transform.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\geometry\preset\Circle2D.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\geometry\preset\Square2D.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\material\SyaroDefaultGBufEmitter.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\physics\artemis\mpm\MPMParticleContainer.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\physics\artemis\mpm\MPMParticleEmitter.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\physics\artemis\mpm\MPMSimulatorConfigurator.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\physics\artemis\pbd\PBDCloth.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\physics\artemis\rigid\GpuRigidCollider.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\renderer\ayanami\AyanamiMeshDF.h"
#include "E:/Projects/Ifrit-v2/include/ifrit/runtime\renderer\ayanami\AyanamiMeshMarker.h"
namespace Ifrit::Reflection
{
    void RegisterReflectionTypes()
    {

        // Ifrit::Runtime::AssetReferenceId
        RegisterType<Ifrit::Runtime::AssetReferenceId>();
        RegisterPropertyField<&Ifrit::Runtime::AssetReferenceId::mType>("Type");
        RegisterPropertyField<&Ifrit::Runtime::AssetReferenceId::mGuid>("Guid");
        RegisterPropertyField<&Ifrit::Runtime::AssetReferenceId::mRelativePath>("Relative Path");

        // Ifrit::Runtime::AssetMetadata
        RegisterType<Ifrit::Runtime::AssetMetadata>();
        RegisterPropertyField<&Ifrit::Runtime::AssetMetadata::mGuid>("Guid");
        RegisterPropertyField<&Ifrit::Runtime::AssetMetadata::mName>("Name");
        RegisterPropertyField<&Ifrit::Runtime::AssetMetadata::mExternalPath>("External Path");
        RegisterPropertyField<&Ifrit::Runtime::AssetMetadata::mImporter>("Importer");
        RegisterPropertyField<&Ifrit::Runtime::AssetMetadata::mReferencingType>("Referencing Type");

        // Ifrit::Runtime::Asset
        RegisterType<Ifrit::Runtime::Asset>();
        RegisterPropertyField<&Ifrit::Runtime::Asset::mMetadata>("Metadata");

        // Ifrit::Runtime::InternalAssetHolder
        RegisterType<Ifrit::Runtime::InternalAssetHolder>();
        RegisterPropertyField<&Ifrit::Runtime::InternalAssetHolder::mAsset>("Asset");

        // Ifrit::Runtime::IAssetImporter
        RegisterType<Ifrit::Runtime::IAssetImporter>();

        // Ifrit::Runtime::AssetManager
        RegisterType<Ifrit::Runtime::AssetManager>();
        RegisterPropertyField<&Ifrit::Runtime::AssetManager::mAssets>("Assets");

        // Ifrit::Runtime::Prefab
        RegisterType<Ifrit::Runtime::Prefab>();
        RegisterPropertyField<&Ifrit::Runtime::Prefab::mSerializedData>("Serialized Data");

        // Ifrit::Runtime::ComponentManager
        RegisterType<Ifrit::Runtime::ComponentManager>();
        RegisterPropertyField<&Ifrit::Runtime::ComponentManager::mComponentArray>("Component Array");
        RegisterPropertyField<&Ifrit::Runtime::ComponentManager::mIdToTypeHash>("Id To Type Hash");
        RegisterPropertyField<&Ifrit::Runtime::ComponentManager::mAllocatedComponents>("Allocated Components");

        // Ifrit::Runtime::GameObjectManager
        RegisterType<Ifrit::Runtime::GameObjectManager>();
        RegisterPropertyField<&Ifrit::Runtime::GameObjectManager::mGameObjects>("Game Objects");
        RegisterPropertyField<&Ifrit::Runtime::GameObjectManager::mAllocatedObjects>("Allocated Objects");

        // Ifrit::Runtime::GameObject
        RegisterType<Ifrit::Runtime::GameObject>();
        RegisterPropertyField<&Ifrit::Runtime::GameObject::mManagedIndex>("Managed Index");
        RegisterPropertyField<&Ifrit::Runtime::GameObject::mIdInParent>("Id In Parent");
        RegisterPropertyField<&Ifrit::Runtime::GameObject::mGuid>("Guid");
        RegisterPropertyField<&Ifrit::Runtime::GameObject::mName>("Name");
        RegisterPropertyField<&Ifrit::Runtime::GameObject::mComponentsHashed>("Components Hashed");

        // Ifrit::Runtime::Component
        RegisterType<Ifrit::Runtime::Component>();
        RegisterPropertyField<&Ifrit::Runtime::Component::mId>("Id");
        RegisterPropertyField<&Ifrit::Runtime::Component::mName>("Name");
        RegisterPropertyField<&Ifrit::Runtime::Component::mGuid>("Guid");
        RegisterPropertyField<&Ifrit::Runtime::Component::mManagedIndex>("Managed Index");
        RegisterPropertyField<&Ifrit::Runtime::Component::mArrayIndex>("Array Index");
        RegisterPropertyField<&Ifrit::Runtime::Component::mEnabled>("Enabled");
        RegisterPropertyHint<&Ifrit::Runtime::Component::mEnabled>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Component::mEnabled>("UISelect", "");

        // Ifrit::Runtime::Camera
        RegisterType<Ifrit::Runtime::Camera>();
        RegisterPolymorphicRelation<Ifrit::Runtime::Camera, Ifrit::Runtime::Component>();
        RegisterPropertyField<&Ifrit::Runtime::Camera::mType>("Type");
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mType>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mType>("UISelect", "");
        RegisterPropertyField<&Ifrit::Runtime::Camera::mFov>("Fov");
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mFov>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mFov>("UISlider.min", (double)0.1);
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mFov>("UISlider.max", (double)180);
        RegisterPropertyField<&Ifrit::Runtime::Camera::mOrthoSpaceSize>("Ortho Space Size");
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mOrthoSpaceSize>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mOrthoSpaceSize>("UISlider.min", (double)0.1);
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mOrthoSpaceSize>("UISlider.max", (double)1000);
        RegisterPropertyField<&Ifrit::Runtime::Camera::mAspect>("Aspect");
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mAspect>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mAspect>("UISlider.min", (double)0.1);
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mAspect>("UISlider.max", (double)10);
        RegisterPropertyField<&Ifrit::Runtime::Camera::mNear>("Near");
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mNear>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mNear>("UISlider.min", (double)0.1);
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mNear>("UISlider.max", (double)1000);
        RegisterPropertyField<&Ifrit::Runtime::Camera::mFar>("Far");
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mFar>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mFar>("UISlider.min", (double)0.1);
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mFar>("UISlider.max", (double)10000);
        RegisterPropertyField<&Ifrit::Runtime::Camera::mIsMainCamera>("Is Main Camera");
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mIsMainCamera>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Camera::mIsMainCamera>("UISelect", "");

        // Ifrit::Runtime::SceneNode
        RegisterType<Ifrit::Runtime::SceneNode>();
        RegisterPropertyField<&Ifrit::Runtime::SceneNode::mName>("Name");
        RegisterPropertyField<&Ifrit::Runtime::SceneNode::mGuid>("Guid");
        RegisterPropertyField<&Ifrit::Runtime::SceneNode::mChildren>("Children");
        RegisterPropertyField<&Ifrit::Runtime::SceneNode::mGameObjectRefs>("Game Object Refs");

        // Ifrit::Runtime::Scene
        RegisterType<Ifrit::Runtime::Scene>();
        RegisterPropertyField<&Ifrit::Runtime::Scene::mComponentManager>("Component Manager");
        RegisterPropertyField<&Ifrit::Runtime::Scene::mGameObjectManager>("Game Object Manager");
        RegisterPropertyField<&Ifrit::Runtime::Scene::mSceneNodes>("Scene Nodes");
        RegisterPropertyField<&Ifrit::Runtime::Scene::mRoot>("Root");

        // Ifrit::Runtime::PrefabAsset
        RegisterType<Ifrit::Runtime::PrefabAsset>();
        RegisterPolymorphicRelation<Ifrit::Runtime::PrefabAsset, Ifrit::Runtime::Asset>();

        // Ifrit::Runtime::GameObjectPrefabAsset
        RegisterType<Ifrit::Runtime::GameObjectPrefabAsset>();
        RegisterPolymorphicRelation<Ifrit::Runtime::GameObjectPrefabAsset, Ifrit::Runtime::PrefabAsset>();

        // Ifrit::Runtime::GameObjectPrefabImporter
        RegisterType<Ifrit::Runtime::GameObjectPrefabImporter>();
        RegisterPolymorphicRelation<Ifrit::Runtime::GameObjectPrefabImporter, Ifrit::Runtime::IAssetImporter>();

        // Ifrit::Runtime::VDBAssetImporter
        RegisterType<Ifrit::Runtime::VDBAssetImporter>();
        RegisterPolymorphicRelation<Ifrit::Runtime::VDBAssetImporter, Ifrit::Runtime::IAssetImporter>();

        // Ifrit::Runtime::MaterialAsset
        RegisterType<Ifrit::Runtime::MaterialAsset>();
        RegisterPolymorphicRelation<Ifrit::Runtime::MaterialAsset, Ifrit::Runtime::Asset>();

        // Ifrit::Runtime::MeshAsset
        RegisterType<Ifrit::Runtime::MeshAsset>();
        RegisterPolymorphicRelation<Ifrit::Runtime::MeshAsset, Ifrit::Runtime::Asset>();

        // Ifrit::Runtime::ImportedMeshAsset
        RegisterType<Ifrit::Runtime::ImportedMeshAsset>();
        RegisterPolymorphicRelation<Ifrit::Runtime::ImportedMeshAsset, Ifrit::Runtime::MeshAsset>();

        // Ifrit::Runtime::WaveFrontAsset
        RegisterType<Ifrit::Runtime::WaveFrontAsset>();
        RegisterPolymorphicRelation<Ifrit::Runtime::WaveFrontAsset, Ifrit::Runtime::ImportedMeshAsset>();

        // Ifrit::Runtime::ShaderAsset
        RegisterType<Ifrit::Runtime::ShaderAsset>();
        RegisterPolymorphicRelation<Ifrit::Runtime::ShaderAsset, Ifrit::Runtime::Asset>();

        // Ifrit::Runtime::TextureAsset
        RegisterType<Ifrit::Runtime::TextureAsset>();
        RegisterPolymorphicRelation<Ifrit::Runtime::TextureAsset, Ifrit::Runtime::Asset>();

        // Ifrit::Runtime::TempPrefabSerializationData
        RegisterType<Ifrit::Runtime::TempPrefabSerializationData>();
        RegisterPropertyField<&Ifrit::Runtime::TempPrefabSerializationData::mGameObject>("Game Object");
        RegisterPropertyField<&Ifrit::Runtime::TempPrefabSerializationData::mComponents>("Components");

        // Ifrit::Runtime::VolumeAsset
        RegisterType<Ifrit::Runtime::VolumeAsset>();
        RegisterPolymorphicRelation<Ifrit::Runtime::VolumeAsset, Ifrit::Runtime::Asset>();

        // Ifrit::Runtime::VDBAsset
        RegisterType<Ifrit::Runtime::VDBAsset>();
        RegisterPolymorphicRelation<Ifrit::Runtime::VDBAsset, Ifrit::Runtime::VolumeAsset>();

        // Ifrit::Runtime::ActorBehavior
        RegisterType<Ifrit::Runtime::ActorBehavior>();
        RegisterPolymorphicRelation<Ifrit::Runtime::ActorBehavior, Ifrit::Runtime::Component>();

        // Ifrit::Runtime::Light
        RegisterType<Ifrit::Runtime::Light>();
        RegisterPolymorphicRelation<Ifrit::Runtime::Light, Ifrit::Runtime::Component>();
        RegisterPropertyField<&Ifrit::Runtime::Light::mType>("Type");
        RegisterPropertyField<&Ifrit::Runtime::Light::AffectPbrSky>("ffect Pbr Sky");
        RegisterPropertyField<&Ifrit::Runtime::Light::ShadowMap>("hadow Map");
        RegisterPropertyField<&Ifrit::Runtime::Light::ShadowMapResolution>("hadow Map Resolution");

        // Ifrit::Runtime::MeshFilter
        RegisterType<Ifrit::Runtime::MeshFilter>();
        RegisterPolymorphicRelation<Ifrit::Runtime::MeshFilter, Ifrit::Runtime::Component>();
        RegisterPropertyField<&Ifrit::Runtime::MeshFilter::mMesh>("Mesh");
        RegisterPropertyHint<&Ifrit::Runtime::MeshFilter::mMesh>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::MeshFilter::mMesh>("AssetCategory", "Mesh");

        // Ifrit::Runtime::MeshRenderer
        RegisterType<Ifrit::Runtime::MeshRenderer>();
        RegisterPolymorphicRelation<Ifrit::Runtime::MeshRenderer, Ifrit::Runtime::Component>();
        RegisterPropertyField<&Ifrit::Runtime::MeshRenderer::mMaterial>("Material");
        RegisterPropertyHint<&Ifrit::Runtime::MeshRenderer::mMaterial>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::MeshRenderer::mMaterial>("AssetCategory", "Material");

        // Ifrit::Runtime::Transform
        RegisterType<Ifrit::Runtime::Transform>();
        RegisterPolymorphicRelation<Ifrit::Runtime::Transform, Ifrit::Runtime::Component>();
        RegisterPropertyField<&Ifrit::Runtime::Transform::mUpdateDevice>("Update Device");
        RegisterPropertyHint<&Ifrit::Runtime::Transform::mUpdateDevice>("Visible", "");
        RegisterPropertyHint<&Ifrit::Runtime::Transform::mUpdateDevice>("UISelect", "");
        RegisterPropertyField<&Ifrit::Runtime::Transform::mPosition>("Position");
        RegisterPropertyHint<&Ifrit::Runtime::Transform::mPosition>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Transform::mPosition>("UIText", "");
        RegisterPropertyField<&Ifrit::Runtime::Transform::mRotation>("Rotation");
        RegisterPropertyHint<&Ifrit::Runtime::Transform::mRotation>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Transform::mRotation>("UIText", "");
        RegisterPropertyField<&Ifrit::Runtime::Transform::mScale>("Scale");
        RegisterPropertyHint<&Ifrit::Runtime::Transform::mScale>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Transform::mScale>("UIText", "");

        // Ifrit::Runtime::Geometry::Circle2DAsset
        RegisterType<Ifrit::Runtime::Geometry::Circle2DAsset>();
        RegisterPolymorphicRelation<Ifrit::Runtime::Geometry::Circle2DAsset, Ifrit::Runtime::MeshAsset>();
        RegisterPropertyField<&Ifrit::Runtime::Geometry::Circle2DAsset::mRadius>("Radius");
        RegisterPropertyField<&Ifrit::Runtime::Geometry::Circle2DAsset::mDivisions>("Divisions");

        // Ifrit::Runtime::Geometry::Square2DAsset
        RegisterType<Ifrit::Runtime::Geometry::Square2DAsset>();
        RegisterPolymorphicRelation<Ifrit::Runtime::Geometry::Square2DAsset, Ifrit::Runtime::MeshAsset>();
        RegisterPropertyField<&Ifrit::Runtime::Geometry::Square2DAsset::mWidth>("Width");
        RegisterPropertyField<&Ifrit::Runtime::Geometry::Square2DAsset::mHeight>("Height");

        // Ifrit::Runtime::DefaultMaterialAsset
        RegisterType<Ifrit::Runtime::DefaultMaterialAsset>();
        RegisterPolymorphicRelation<Ifrit::Runtime::DefaultMaterialAsset, Ifrit::Runtime::MaterialAsset>();

        // Ifrit::Runtime::Artemis::MPMParticleContainer
        RegisterType<Ifrit::Runtime::Artemis::MPMParticleContainer>();
        RegisterPolymorphicRelation<Ifrit::Runtime::Artemis::MPMParticleContainer, Ifrit::Runtime::Component>();
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMParticleContainer::mMaxParticleCount>("Max Particle Count");

        // Ifrit::Runtime::Artemis::MPMParticleEmitter
        RegisterType<Ifrit::Runtime::Artemis::MPMParticleEmitter>();
        RegisterPolymorphicRelation<Ifrit::Runtime::Artemis::MPMParticleEmitter, Ifrit::Runtime::Component>();
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitTriggerType>("Emit Trigger Type");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitTriggerType>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitTriggerType>("UISelect", "");
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitMaterialType>("Emit Material Type");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitMaterialType>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitMaterialType>("UISelect", "");
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitSampleSource>("Emit Sample Source");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitSampleSource>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitSampleSource>("UISelect", "");
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitColor>("Emit Color");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitColor>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitColor>("UIColor", "");
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitMinRange>("Emit Min Range");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitMinRange>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitMinRange>("UIText", "");
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitMaxRange>("Emit Max Range");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitMaxRange>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitMaxRange>("UIText", "");
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitInterval>("Emit Interval");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitInterval>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitInterval>("UISlider.min", (int)5);
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mEmitInterval>("UISlider.max", (int)1000);
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mParticleMass>("Particle Mass");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mParticleMass>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mParticleMass>("UISlider.min", (double)0.001);
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mParticleMass>("UISlider.max", (double)5);
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mSamplerPpc>("Sampler Ppc");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mSamplerPpc>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mSamplerPpc>("UISlider.min", (int)1);
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mSamplerPpc>("UISlider.max", (int)20);
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mCellDx>("Cell Dx");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mCellDx>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mCellDx>("UISlider.min", (double)0.1);
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mCellDx>("UISlider.max", (double)2);
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mVdbSampleSource>("Vdb Sample Source");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mVdbSampleSource>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMParticleEmitter::mVdbSampleSource>("AssetCategory", "VolumetricData");
        RegisterMethodField<&Ifrit::Runtime::Artemis::MPMParticleEmitter::ImmediateEmit>("Immediate Emit");

        // Ifrit::Runtime::Artemis::MPMSimulatorConfigurator
        RegisterType<Ifrit::Runtime::Artemis::MPMSimulatorConfigurator>();
        RegisterPolymorphicRelation<Ifrit::Runtime::Artemis::MPMSimulatorConfigurator, Ifrit::Runtime::Component>();
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mMpmSubsteps>("Mpm Substeps");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mMpmSubsteps>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mMpmSubsteps>("UISlider.min", (int)1);
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mMpmSubsteps>("UISlider.max", (int)10);
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPbmpmIterations>("Pbmpm Iterations");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPbmpmIterations>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPbmpmIterations>("UISlider.min", (int)1);
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPbmpmIterations>("UISlider.max", (int)100);
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPbmpmElasticityRatio>("Pbmpm Elasticity Ratio");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPbmpmElasticityRatio>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPbmpmElasticityRatio>("UISlider.min", (double)0);
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPbmpmElasticityRatio>("UISlider.max", (double)1);
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPbmpmElasticityRelax>("Pbmpm Elasticity Relax");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPbmpmElasticityRelax>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPbmpmElasticityRelax>("UISlider.min", (double)0);
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPbmpmElasticityRelax>("UISlider.max", (double)5);
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mGravity>("Gravity");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mGravity>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mGravity>("UIText", "");
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPointSize>("Point Size");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPointSize>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPointSize>("UISlider.min", (double)0.1);
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mPointSize>("UISlider.max", (double)5);
        RegisterPropertyField<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mEnableRigidCoupling>("Enable Rigid Coupling");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mEnableRigidCoupling>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::mEnableRigidCoupling>("UISelect", "");
        RegisterMethodField<&Ifrit::Runtime::Artemis::MPMSimulatorConfigurator::ClearScene>("Clear Scene");

        // Ifrit::Runtime::Ayanami::AyanamiMeshDF
        RegisterType<Ifrit::Runtime::Ayanami::AyanamiMeshDF>();
        RegisterPolymorphicRelation<Ifrit::Runtime::Ayanami::AyanamiMeshDF, Ifrit::Runtime::Component>();

        // Ifrit::Runtime::Artemis::PBDCloth
        RegisterType<Ifrit::Runtime::Artemis::PBDCloth>();
        RegisterPolymorphicRelation<Ifrit::Runtime::Artemis::PBDCloth, Ifrit::Runtime::Component>();
        RegisterPropertyField<&Ifrit::Runtime::Artemis::PBDCloth::mDefaultBendingStiffness>("Default Bending Stiffness");
        RegisterPropertyField<&Ifrit::Runtime::Artemis::PBDCloth::mDefaultStretchingStiffness>("Default Stretching Stiffness");

        // Ifrit::Runtime::Artemis::GPURigidCollider
        RegisterType<Ifrit::Runtime::Artemis::GPURigidCollider>();
        RegisterPolymorphicRelation<Ifrit::Runtime::Artemis::GPURigidCollider, Ifrit::Runtime::Component>();
        RegisterPropertyField<&Ifrit::Runtime::Artemis::GPURigidCollider::mCuboidSize>("Cuboid Size");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::GPURigidCollider::mCuboidSize>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::GPURigidCollider::mCuboidSize>("UIText", "");
        RegisterPropertyField<&Ifrit::Runtime::Artemis::GPURigidCollider::mRadius>("Radius");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::GPURigidCollider::mRadius>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::GPURigidCollider::mRadius>("UIText", "");
        RegisterPropertyField<&Ifrit::Runtime::Artemis::GPURigidCollider::mRigidMass>("Rigid Mass");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::GPURigidCollider::mRigidMass>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::GPURigidCollider::mRigidMass>("UIText", "");
        RegisterPropertyField<&Ifrit::Runtime::Artemis::GPURigidCollider::mType>("Type");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::GPURigidCollider::mType>("Editable", "");
        RegisterPropertyHint<&Ifrit::Runtime::Artemis::GPURigidCollider::mType>("UISelect", "");

        // Ifrit::Runtime::Ayanami::AyanamiMeshMarker
        RegisterType<Ifrit::Runtime::Ayanami::AyanamiMeshMarker>();
        RegisterPolymorphicRelation<Ifrit::Runtime::Ayanami::AyanamiMeshMarker, Ifrit::Runtime::Component>();
    }
}
