// ****************************************************************
// This file is auto-generated by ifrit.reflparser.
// Do not edit this file manually.
// ****************************************************************

#pragma once
#include "ifrit/core/reflection/Reflection.h"

namespace Ifrit::Reflection
{
    void RegisterReflectionTypes();
}
