set(IFRIT_REQ_GLFW3_BASE ${IFRIT_GLOBAL_GLFW_DIR_WINDOWS})
find_package(glfw3 QUIET)
if(NOT glfw3_FOUND)
    include_directories(${IFRIT_REQ_GLFW3_BASE}/include)
	message(STATUS "[IFRIT/EnvCheck]: glfw3 not found, fallback to predefined paths.")
    if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        set(glfw3_LIB ${IFRIT_REQ_GLFW3_BASE}/lib/glfw3.lib)
    else()
        if(CMAKE_SYSTEM_NAME STREQUAL "Windows" OR MINGW)
            set(glfw3_LIB ${IFRIT_REQ_GLFW3_BASE}/lib/libglfw3.a)
        else()
            set(glfw3_LIB ${IFRIT_REQ_GLFW3_BASE}/lib/libglfw3.so)
        endif()
    endif()
    # Check if file exists
    if(NOT EXISTS ${glfw3_LIB})
        message(STATUS "[IFRIT/EnvCheck]: Cannot find glfw3 in ${glfw3_LIB}")
		message(FATAL_ERROR "[IFRIT/EnvCheck]: glfw3 not found, please install glfw3 or set the correct path.")
    else()
        message(STATUS "[IFRIT/EnvCheck]: glfw3 found")
    endif()
else()
	message(STATUS "[IFRIT/EnvCheck]: glfw3 found")
    set(GLFW3_LINK_TARGET glfw)
    include_directories(${GLFW_INCLUDE_DIRS})
endif()