#pragma once
namespace Ifrit::Engine {
	enum IfritPolygonMode {
		IF_POLYGON_MODE_FILL = 0,
		IF_POLYGON_MODE_LINE = 1,
		IF_POLYGON_MODE_POINT = 2
	};
	enum IfritSamplerAddressMode {
		IF_SAMPLER_ADDRESS_MODE_REPEAT = 0,
		IF_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT = 1,
		IF_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE = 2,
		IF_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER = 3,
		IF_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE = 4,
	};
	enum IfritFilter {
		IF_FILTER_NEAREST = 0,
		IF_FILTER_LINEAR = 1
	};
	enum IfritBorderColor {
		IF_BORDER_COLOR_BLACK = 0,
		IF_BORDER_COLOR_WHITE = 1
	};
	enum IfritImageTiling {
		IF_IMAGE_TILING_LINEAR=1
	};
}