// ****************************************************************
// This file is auto-generated by ifrit.reflparser.
// Do not edit this file manually.
// ****************************************************************

#include "ifrit/core/reflection/Reflection.h"

// Begin Body
#include "C:/WR/Ifrit-v2/include/ifrit/runtime/base\ActorBehavior.h"
#include "C:/WR/Ifrit-v2/include/ifrit/runtime/base\ApplicationInterface.h"
#include "C:/WR/Ifrit-v2/include/ifrit/runtime/base\AssetReference.h"
#include "C:/WR/Ifrit-v2/include/ifrit/runtime/base\Base.h"
#include "C:/WR/Ifrit-v2/include/ifrit/runtime/base\Camera.h"
#include "C:/WR/Ifrit-v2/include/ifrit/runtime/base\Component.h"
#include "C:/WR/Ifrit-v2/include/ifrit/runtime/base\Light.h"
#include "C:/WR/Ifrit-v2/include/ifrit/runtime/base\Material.h"
#include "C:/WR/Ifrit-v2/include/ifrit/runtime/base\Mesh.h"
#include "C:/WR/Ifrit-v2/include/ifrit/runtime/base\MeshComponent.h"
#include "C:/WR/Ifrit-v2/include/ifrit/runtime/base\MeshTransform.h"
#include "C:/WR/Ifrit-v2/include/ifrit/runtime/base\Property.h"
#include "C:/WR/Ifrit-v2/include/ifrit/runtime/base\Scene.h"
#include "C:/WR/Ifrit-v2/include/ifrit/runtime/base\Transform.h"
namespace Ifrit::Reflection
{
    void RegisterReflectionTypes()
    {
        RegisterType<Ifrit::Runtime::GameObject>();
        RegisterPropertyField<&Ifrit::Runtime::GameObject::m_ComponentsHashed>("M_ Components Hashed");
        RegisterType<Ifrit::Runtime::Component>();
        RegisterPropertyField<&Ifrit::Runtime::Component::m_isEnabled>("M_is Enabled");
        RegisterType<Ifrit::Runtime::ActorBehavior>();
        RegisterType<Ifrit::Runtime::Camera>();
        RegisterType<Ifrit::Runtime::Light>();
        RegisterType<Ifrit::Runtime::MeshFilter>();
        RegisterType<Ifrit::Runtime::MeshRenderer>();
        RegisterType<Ifrit::Runtime::Transform>();
    }
}
